"""Initial schema with users, documents, search, feedback tables

Revision ID: f448da6ffc1c
Revises: 
Create Date: 2026-01-01 11:46:59.658500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f448da6ffc1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the document'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full document content for reference'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document type: PDF, DOCX, TXT, MARKDOWN'),
    sa.Column('source', sa.String(length=500), nullable=False, comment='Original file path or URL'),
    sa.Column('access_level', sa.Integer(), nullable=False, comment='Required access level: 1=Public, 2=Internal, 3=Confidential'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='Department that owns this document (nullable for public docs)'),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata in JSON format (with GIN index)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_access_level'), 'documents', ['access_level'], unique=False)
    op.create_index(op.f('ix_documents_department'), 'documents', ['department'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (unique, indexed)"),
    sa.Column('name', sa.String(length=100), nullable=False, comment="User's full name"),
    sa.Column('department', sa.String(length=50), nullable=False, comment='Department for access control'),
    sa.Column('access_level', sa.Integer(), nullable=False, comment='Access level: 1=Public, 2=Internal, 3=Confidential'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the search query'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who made the query'),
    sa.Column('query', sa.Text(), nullable=False, comment='The search query text'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='Optional session ID for grouping queries'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the query was made'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_queries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries'))
    )
    op.create_index(op.f('ix_search_queries_timestamp'), 'search_queries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('search_responses',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the search response'),
    sa.Column('query_id', sa.UUID(), nullable=False, comment='The query this response belongs to (one-to-one)'),
    sa.Column('answer', sa.Text(), nullable=False, comment='The generated answer text'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON array of source documents with metadata'),
    sa.Column('response_time_ms', sa.Integer(), nullable=False, comment='Time taken to generate response in milliseconds'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the response was generated'),
    sa.ForeignKeyConstraint(['query_id'], ['search_queries.id'], name=op.f('fk_search_responses_query_id_search_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_responses'))
    )
    op.create_index(op.f('ix_search_responses_query_id'), 'search_responses', ['query_id'], unique=True)
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the feedback'),
    sa.Column('query_id', sa.UUID(), nullable=False, comment='The query this feedback is for'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The user who provided this feedback'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='User rating from 1 to 5'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional text comment from user'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the feedback was submitted'),
    sa.ForeignKeyConstraint(['query_id'], ['search_queries.id'], name=op.f('fk_user_feedback_query_id_search_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_feedback'))
    )
    op.create_index(op.f('ix_user_feedback_query_id'), 'user_feedback', ['query_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)

    # Add GIN index for JSONB metadata column
    op.create_index(
        'ix_documents_doc_metadata',
        'documents',
        ['doc_metadata'],
        postgresql_using='gin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop GIN index for JSONB metadata column
    op.drop_index('ix_documents_doc_metadata', table_name='documents')

    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_query_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_search_responses_query_id'), table_name='search_responses')
    op.drop_table('search_responses')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_timestamp'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_department'), table_name='documents')
    op.drop_index(op.f('ix_documents_access_level'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
